name: PR Merged

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to main
    runs-on: ubuntu-latest
    steps:
      - name: Trigger nhs-notify-internal static environment workflow deployment
        shell: bash
        run: |
          set -x
          this_repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)

          DISPATCH_EVENT=$(jq -ncM \
            --arg infraRepoName "${this_repo_name}" \
            --arg releaseVersion "main" \
            --arg targetEnvironment "main" \
            --arg targetAccountGroup "nhs-notify-web-dev" \
            --arg targetComponent "cdn" \
            --arg terraformAction "apply" \
            '{ "ref": "main",
              "inputs": {
                "infraRepoName": $infraRepoName,
                "releaseVersion", $releaseVersion,
                "targetEnvironment", $targetEnvironment,
                "targetAccountGroup", $targetAccountGroup,
                "targetComponent", $targetComponent,
                "terraformAction", $terraformAction
              }
            }')

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/workflows/dispatch-deploy-static-env.yaml/dispatches \
            -d "${DISPATCH_EVENT}"
