name: PR Merged

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to main
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        component: [acct, cdn]

    steps:
      - uses: actions/checkout@v4

      - name: Trigger nhs-notify-internal static environment workflow deployments
        uses: ./.github/workflows/trigger_internal_repo_build.yaml
        with:
          secrets: inherit
          release_version: main
          tf_environment: "main"
          tf_group: "nhs-notify-web-dev"
          tf_component: ${{ matrix.component }}
          tf_action: "apply"
